### ISSUE TITLE
Incorporate linting for this repository

### ISSUE THREAD

**Issue by rexagod** [IBM/ibm-storage-odf-console#20]
Hello.

There are no linting pre-commit hooks present in this repository at the moment. I suggest adding `husky` and `eslint` to implement this functionality. Here are a few leads.

* [Incorporate `husky` into this codebase for pre-commit hooks](https://github.com/openshift/console/blob/b5fb17372529943a923d62eb5ad604ed18544dc1/frontend/package.json#L331-L338)
* [Default `eslint` command to use in the repository-wide `package.json` when checking for lint errors](https://github.com/openshift/console/blob/b5fb17372529943a923d62eb5ad604ed18544dc1/frontend/package.json#L19-L20).
* [Extend `prettier` in `eslint` configs](https://github.com/rexagod/console/blob/master/frontend/packages/ceph-storage-plugin/.eslintrc#L3) (refer [this](https://github.com/rexagod/console/blob/8135af447bd8c3ee188af47abf10665b3bbb3498/frontend/packages/eslint-plugin-console/index.js#L27-L40)), and add [`imports` linting](https://github.com/rexagod/console/blob/8135af447bd8c3ee188af47abf10665b3bbb3498/frontend/packages/ceph-storage-plugin/.eslintrc#L5-L27).
* Although I do not see any styling files here, it'd be good to note that we can [use `styleint` to lint those whenever the need be](https://github.com/openshift/console/pull/8360/files#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655).

Thanks.

**Comment by rexagod** [comment]
@shdn-ibm I think #22 only partially addressed the third point. Please reopen, thanks.

**Comment by shdn-ibm** [comment]
Hi, @rexagod . I use git workflow hook to realize this. See https://github.com/IBM/ibm-storage-odf-console/blob/main/.github/workflows/eslint.yaml

**Comment by rexagod** [comment]
Yeah I saw that. However, the story was more along the lines of preventing a commit to happen if the lint checks don't pass, rather that committing lint errors on a branch and fixing that after GitHub reports those, which I think slows down the whole workflow.

Thanks.

**Comment by shdn-ibm** [comment]
add husky:  https://github.com/IBM/ibm-storage-odf-console/pull/23

**Comment by rexagod** [comment]
Nice, did you incorporate the [`imports` linting](https://github.com/rexagod/console/blob/8135af447bd8c3ee188af47abf10665b3bbb3498/frontend/packages/ceph-storage-plugin/.eslintrc#L5-L27) as well? This could potentially save devs working on this repository from a plethora of merge conflicts.

**Comment by shdn-ibm** [comment]
No, this repository does not have the `eslint-plugin-console` or the `import/order` rule

**Comment by rexagod** [comment]
I would suggest we incorporate this change for less overhead in the future.

**Comment by shdn-ibm** [comment]
I notice in console, it is defined in package `eslint-plugin-console`, there are some files to define the rule. Is there any method to extract the rule simply, instead of copy the file into this repo.
