### ISSUE TITLE
The IBM Storage ODF Operator shows up in both Installed Operator and and Operator Hub for Install

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#31]
In the Operator Hub panel.  It shows that version 0.21 can be installed
![Screen Shot 2021-09-17 at 10 43 51 AM](https://user-images.githubusercontent.com/31971013/133816507-df6a53ab-7958-4a9d-bbea-eeadf5238421.png)
![Screen Shot 2021-09-17 at 10 44 07 AM](https://user-images.githubusercontent.com/31971013/133816562-7b385f1c-01cd-4dd0-a2cb-91ff31bdefdd.png)

This next screen shot shows the same operator and version is installed
![Screen Shot 2021-09-17 at 10 46 36 AM](https://user-images.githubusercontent.com/31971013/133816902-082889b7-b6d8-4115-871b-56b6a77a08fd.png)

This is on test system cluster2.

**Comment by MonicaLemay** [comment]
![Screen Shot 2021-09-21 at 11 08 25 AM](https://user-images.githubusercontent.com/31971013/134206905-82329a47-30e6-4175-a9a4-a7b3d4e679ad.png)

Notice how the OpenShift Data Foundation has a green circle with a white check mark and the word "Installed"
The IBM  Storage ODF Operator does not have that.  


When I click on OpenShift Data Foundation, because it is already installed, I get an "Unistall Button"
<img width="588" alt="Screen Shot 2021-09-21 at 11 10 24 AM" src="https://user-images.githubusercontent.com/31971013/134207185-49d79ce1-f436-4e2d-b4f1-b7b06741742c.png">

When I click on IBM Storage ODF Operator, I get an "install" button.
<img width="511" alt="Screen Shot 2021-09-21 at 11 11 24 AM" src="https://user-images.githubusercontent.com/31971013/134207331-7becc2e4-fe0d-4f7c-86aa-d856cb5f5f1f.png">


I don't know what the correct behaviour should be but I would think that consistency and accurate reporting is important to the customer

**Comment by shdn-ibm** [comment]
IBM Operator should not be installed individually. We should document it in the user guide

**Comment by shdn-ibm** [comment]
hiding this operator from UI
https://github.com/IBM/ibm-storage-odf-operator/pull/37

**Comment by shdn-ibm** [comment]
fixed in: ibm-storage-operator:0.2.1 image. Please pull this image to verify.

**Comment by MonicaLemay** [comment]
Applied the ibm-storage-operator:0.2.1 and it is indeed fixed.  I am closing this issue.
