### ISSUE TITLE
Blank page after selecting the Flash storage system

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#32]
This problem is on cluster2.  There is a spread sheet in the box  note that provides IP address and login credentials.

In the OpenShift Data Foundation -> Storage Systems panel, after clicking on the " ibm-flashsystem-storage-storagesystem" the next page is blank.
![Screen Shot 2021-09-20 at 2 02 11 PM](https://user-images.githubusercontent.com/31971013/134059442-cd24d251-b7ed-4812-9e5f-84400d070cd1.png)

After clicking on ibm-flashsystem-storage-storagesystem, the next page is blank.  It is not blank if click on ocs-storagecluster-storagesystem.  

![Screen Shot 2021-09-20 at 2 03 19 PM](https://user-images.githubusercontent.com/31971013/134059565-1a694e46-3f93-462e-a86d-228767aea246.png)

**Comment by MonicaLemay** [comment]
I was able to recreate this all day yesterday.  However today I cannot.  Today I see details.
![Screen Shot 2021-09-21 at 11 03 17 AM](https://user-images.githubusercontent.com/31971013/134206121-fa94ac09-76c4-4e32-a725-d323f6bc92ac.png)

Does it take a long time to create the storage system and populate the info?
 It appears that it takes about 1 hour or so.

**Comment by shdn-ibm** [comment]
Investigation in progess

**Comment by MonicaLemay** [comment]
I think the page is blank b/c of the distance.  If I hit refresh, the panel is displayed.

**Comment by shdn-ibm** [comment]
submit an issue to odf-console: https://bugzilla.redhat.com/show_bug.cgi?id=2013086

**Comment by shdn-ibm** [comment]
fix is in quay.io/ocs-dev/odf-console:latest
please verify.

**Comment by lbscorpio** [comment]
The fix was already verified and included in 1.0.0, closed the ticket. Thanks.
