### ISSUE TITLE
After deleting the IBM FlashSystem Storage System, the secret was not cleaned up

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#33]
This defect is on cluster2,  there is spreadsheet in the box note that provides information.

After deleting the IBM FlashSystem Storage System, I attempted to create another one.

The following message appeared on the GUI.
![Screen Shot 2021-09-20 at 2 45 25 PM](https://user-images.githubusercontent.com/31971013/134065856-f1c91ac0-1663-43cd-b175-f3c82d17deaa.png)

The secret that was created when the Storage System was created, did not get deleted when the Storage System was deleted.  Because this secret is automatically created, it should be automatically deleted.

The cli also shows the secret is still there.
```
[root@cluster2-inf ~]# oc get secret -n openshift-storage  ibm-flashsystem-storage
NAME                      TYPE     DATA   AGE
ibm-flashsystem-storage   Opaque   3      4d2h
```
You can see that the secret is 4 days old.

![Screen Shot 2021-09-20 at 2 54 26 PM](https://user-images.githubusercontent.com/31971013/134066625-2023dbee-859b-48ad-8762-e228dfbf1b11.png)
This screen shot, above, shows the error that the secret exists.  And it appears that the create storage system fails.  I can keep clicking on it and it shows the same error. 

Oddly,  both the Storage Systems GUI and the cli shows that the storage system is indeed created, despite the error panel.
Both the  CLI and GUI don't indicate that it is only partially created.
``` 
[root@cluster2-inf ~]# oc get storagesystems -A
NAMESPACE           NAME                                    STORAGE-SYSTEM-KIND                       STORAGE-SYSTEM-NAME
openshift-storage   ibm-flashsystem-storage-storagesystem   flashsystemcluster.odf.ibm.com/v1alpha1   ibm-flashsystem-storage
```

![Screen Shot 2021-09-20 at 3 00 40 PM](https://user-images.githubusercontent.com/31971013/134067250-71087d3a-7566-4a86-80f1-2f9504154e04.png)

However a describe of the storage system shows that it is 112 seconds old
```
Events:
  Type     Reason           Age   From                      Message
  ----     ------           ----  ----                      -------
  Warning  ReconcileFailed  112s  StorageSystem controller  FlashSystemCluster.odf.ibm.com "ibm-flashsystem-storage" not found
[root@cluster2-inf ~]#
```

There are really a couple of problems here. 
1) the secret should have been deleted when the storage system was deleted
2) The GUI should indicate that the storage system is partially created

**Comment by shdn-ibm** [comment]
known issue, try to fix it in operator

**Comment by shdn-ibm** [comment]
add below cleanup commend in documentation for user to cleanup
```
oc delete secret -n openshift-storage ibm-flashsystem-storage
```
close.
