### ISSUE TITLE
The Create New Storage System Wizard does not have an "Edit Yaml" button

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#36]
The test plan for the "Create New Storage System  Wizard" says to verify that there is a way to edit the YAML via an" Edit Yaml button" within the wizard.

This is a screen shot of the testplan section.  The last line mentions the edit yaml.
<img width="1072" alt="Screen Shot 2021-09-22 at 11 08 04 AM" src="https://user-images.githubusercontent.com/31971013/134380818-44211a66-0b4f-496b-9eea-3fdeb0ac8c54.png">

I am unable to get a screen shot of the missing "Edit Yaml Button" because after I click "Create" the Wizard exits and there are no more buttons or panels.

There is an ability to edit the yaml from the Storage Systems panel but this is not what the test plan mentions.

<img width="1131" alt="Screen Shot 2021-09-22 at 11 12 20 AM" src="https://user-images.githubusercontent.com/31971013/134381556-fb134385-3619-4cac-9342-91092743f7ea.png">

This is on cluster2 but probably exists on any cluster

**Comment by shdn-ibm** [comment]
Edit Yaml field will not displayed in the page title. It is moved to the edit storagesystem action menu.
Close this as it works as design.
@MonicaLemay Please modify this test case according to the change.
