### ISSUE TITLE
For the Create StorageSystem wizard, there is no documentation,help or explanation for the Advanced option

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#37]
There is an Advanced toggle button that changes from up arrow to down arrow if selected.
![Screen Shot 2021-09-24 at 11 14 31 AM](https://user-images.githubusercontent.com/31971013/134707608-0f674a11-ecf1-4a66-b8f0-03d43fb0e6c6.png)
d 

![Screen Shot 2021-09-24 at 11 16 23 AM](https://user-images.githubusercontent.com/31971013/134707867-e78dd0b6-c20b-41aa-9936-0cb4430566a6.png)

There is a pull down but the only option, there are no docs to explain the Full Deployment and Cloud option

**Comment by afreen23** [comment]
Hey,
We are tracking this in BZ on ODF console https://bugzilla.redhat.com/show_bug.cgi?id=2005902
This issue is required to be fixed in odf console

**Comment by shdn-ibm** [comment]
thanks @afreen23 
Can we close this now? @MonicaLemay
