### ISSUE TITLE
In the Storage Systems wizard,  After Review and Create Panel,  404 error

### ISSUE THREAD

**Issue by MonicaLemay** [IBM/ibm-storage-odf-console#38]
![Screen Shot 2021-09-24 at 11 28 42 AM](https://user-images.githubusercontent.com/31971013/134709383-de249aff-c93c-4584-9b43-69874e5903ff.png)

This was displayed after I clicked the create button.

This was on cluster2.  If you tell me where logs are, I can upload them.

**Comment by MonicaLemay** [comment]
Refresh of the GUI works to display them correctly.

The Admin should not have to do a refresh.

**Comment by shdn-ibm** [comment]
this may be the same issue as #32 
working with Bipul for the root cause

**Comment by shdn-ibm** [comment]
opened https://bugzilla.redhat.com/show_bug.cgi?id=2014395 to ocs console team

**Comment by lbscorpio** [comment]
Redhat might solve it, I can't see the same symptom on 1.0.0 so far, closed the ticket, thanks.
